{
  "clean": true,
  "sdk": "macosx",
  "author": "Galen Rhodes",
  "author_url": "https://blog.projectgalen.com",
  "github_url": "https://github.com/GalenRhodes/Z28",
  "github_file_prefix": "https://github.com/GalenRhodes/Z28/blob/master",
  "theme": "apple",
  "use_safe_filenames": true,
  "min_acl": "public",
  "undocumented_text": "",
  "title": "Z28©",
  "swift_build_tool": "xcodebuild",
  "build_tool_arguments": [ "-scheme", "Z28", ],
  "separate_global_declarations": true,
},
